export const tid = {
  preview: 'preview',
  previewEmpty: 'preview-empty',
  previewImage: 'preview-image',
  previewVideo: 'preview-video',
  previewYoutube: 'preview-youtube',
  previewAudio: 'preview-audio',
  previewAudioYoutube: 'preview-audio-youtube',
  previewTop: 'preview-top',
  previewBottom: 'preview-bottom',
  previewPlay: 'preview-play',
  resizeHandle: 'resize-handle',
  maximize: 'maximize',
  minimize: 'minimize',
  srcInput: 'src-input',
  audioInput: 'audio-input',
  audioNote: 'audio-note',
  topInput: 'top-input',
  bottomInput: 'bottom-input',
  shareButton: 'share-button',
  resetButton: 'reset-button',
  themeToggle: 'theme-toggle',
  toast: 'toast',
} as const;
